version: 1.0.0
name: "payprotocol-sample"

client:
  organization: payprotocol

channels:
  payprotocol:
    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      discovery:
        maxTargets: 2
        retryOpts:
          attempts: 4
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      eventService:
        resolverStrategy: PreferOrg
        balancer: Random
        blockHeightLagThreshold: 5
        reconnectBlockHeightLagThreshold: 8
        peerMonitorPeriod: 6s
    orderers:
      - payprotocol-orderer
    peers:
      payprotocol-peer:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  payprotocol:
    mspid: payprotocol
    peers:
      - payprotocol-peer
    certificateAuthorities:
      - payprotocol-ca

orderers:
  payprotocol-orderer:
    url: grpc://52.79.238.126:7050
    grpcOptions:
      ssl-target-name-override: payprotocol-orderer
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true

peers:
  payprotocol-peer:
    url: grpc://52.79.238.126:7051
    grpcOptions:
      ssl-target-name-override: payprotocol-peer
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true

certificateAuthorities:
  payprotocol-ca:
    caName: payprotocol-rca-001
    url: https://3.35.244.108:7054
    tlsCACerts:
      path: src/main/resources/ca-tls.pem